export const featuredPortfolio = [
  {
    id: 1,
    title: "Optical Character Recognition",
    img: "https://la.mathworks.com/matlabcentral/mlc-downloads/downloads/daea137a-5cd3-485e-9855-ceef8b7ce951/8c87c747-d9db-4653-b2e8-893d4e4cc9b2/images/1617204293.PNG",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89654-optical-character-recognition-ocr?s_tid=srchtitle",
    site: "https://www.youtube.com/watch?v=Ns0gigWsijE",
    description: "(OCR)",
  },
  {
    id: 4,
    title: "Pagina Web",
    img: "assets/images/tienda.png",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/electrocode/",
  },
  {
    id: 5,
    title: "Pagina Web",
    img: "assets/images/ejemplo.png",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/pruebaweb/",
  },
  {
    id: 6,
    title: "Pagina Web",
    img: "assets/images/things.png",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/thingslearned/",
  },
  {
    id: 2,
    title: "Codigos de Lineas",
    img: "https://la.mathworks.com/matlabcentral/mlc-downloads/downloads/b6086d6c-2c90-4677-99c2-83b59ec84502/2c24a7ad-410a-4af9-85cd-3ee766cd9b30/images/1618269106.png",
    link: "https://www.mathworks.com/matlabcentral/fileexchange/89461-codigos-de-lineas",
    site: "https://www.youtube.com/watch?v=Ns0gigWsijE",
    description: "Matlab - Guide",
  },
  {
    id: 3,
    title: "fourier series",
    img: "https://la.mathworks.com/matlabcentral/mlc-downloads/downloads/7544ce00-76bb-40dd-ae64-bdac9554629a/6e7e6cb0-aa24-47a7-a1a1-ed865e9ecee9/images/1616884439.PNG",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89471-fourier-series",
    site: "https://www.youtube.com/watch?v=A4pPMjUCpu4",
    description: "Matlab - Guide",
  },
  {
    id: 4,
    title: "Transformada de Fourier",
    img: "https://la.mathworks.com/matlabcentral/mlc-downloads/downloads/0926d5af-689c-4525-970f-ddc28ce62037/e742d0c9-67cc-41df-85fd-0960e97b6e38/images/1616884683.PNG",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89476-fourier-transform",
    site: "https://www.youtube.com/watch?v=mFPzV0_ZAaU",
    description: "Matlab - Guide",
  },
  {
    id: 5,
    title: "Antena de Onda Progresiva",
    img: "https://la.mathworks.com/matlabcentral/mlc-downloads/downloads/99531845-4005-4440-8ddb-0cc5104f4062/63b04383-fcaf-45a5-b662-d9ab57f3734c/images/1616882985.PNG",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89466-antena-de-onda-progresiva",
    site: "https://www.youtube.com/watch?v=PGiCUdlkhHw",
    description: "Matlab - Guide",
  },
  {
    id: 2,
    title: "ChatBot",
    img: "https://images.unsplash.com/photo-1611746869696-d09bce200020?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    description: "ARDUINO - TELEGRAM",
  },
  {
    id: 6,
    title: "SINGLE STUB SHUNT TUNING",
    img: "https://la.mathworks.com/matlabcentral/mlc-downloads/downloads/742c566e-a278-4e8d-b29c-08f79fb3060a/ff2c2392-d99b-4f5a-b3e5-c6fc117f34e1/images/1616880509.PNG",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89451-single-stub-shunt-tuning",
    site: "https://www.youtube.com/watch?v=g3iBlooyHTw",
    description: "Matlab - Guide",
  },
  {
    id: 7,
    title: "SINGLE STUB SERIES TUNING",
    img: "https://la.mathworks.com/matlabcentral/mlc-downloads/downloads/a4832235-7133-4809-8081-ccfac616edcf/023bc73a-8024-4c03-be78-763983a7eefd/images/1616892993.PNG",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89486-single-stub-series-tuning",
    site: "https://www.youtube.com/watch?v=1RVlOyMxK_k",
    description: "Matlab - Guide",
  },
  {
    id: 8,
    title: "Procesamiento de Imagenes",
    img: "https://i.ytimg.com/vi/12cHkBRj3QY/maxresdefault.jpg",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/96942-proyecto-modulaciones-digitales-aplicado-a-imagenes-matlab",
    site: "https://www.youtube.com/watch?v=12cHkBRj3QY",
    description: "Matlab - Guide",
  },
  {
    id: 9,
    title: "Log Periodic Dipole Antenna",
    img: "https://i.ytimg.com/vi/UgPA1TDpH7Q/mqdefault.jpg",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/96872-log-periodic-antenna",
    site: "https://www.youtube.com/watch?v=eCaaMCwWpmY",
    description: "Matlab - Guide",
  },
  {
    id: 10,
    title: "Modulacion PCM",
    img: "https://i.ytimg.com/vi/2jk2lun9zBs/maxresdefault.jpg",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/97107-modulacion-pcm?s_tid=srchtitle",
    site: "https://www.youtube.com/watch?v=2jk2lun9zBs",
    description: "Matlab - Guide",
  },
  {
    id: 7,
    title: "Pagina Web",
    img: "https://images01.nicepage.com/page/42/02/website-template-preview-42023.jpg",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/food/",
  },
  {
    id: 8,
    title: "Pagina Web",
    img: "assets/images/screencapture-corozco6489-github-io-Bootstrap5Simple-2021-10-18-08_45_57.png",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/Bootstrap5Simple/",
  },

  {
    id: 1,
    title: "ChatBot",
    img: "https://images.unsplash.com/photo-1632435499152-18838be77960?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    link: "https://www.youtube.com/watch?v=vqRQqrNxscw",
    site: "https://www.youtube.com/watch?v=vqRQqrNxscw",
    description: "ARDUINO - WHATSAPP",
  },

  {
    id: 3,
    title: "Modbus Comunicacion",
    img: "assets/images/img-1.jpg",
    link: "https://github.com/Charles6489/modbus_arduino_factory_io_nodered",
    site: "https://www.youtube.com/watch?v=FHhumt2GADU",
  },

  {
    id: 1,
    title: "GooGle Cloud",
    img: "https://images.unsplash.com/photo-1603695576504-b2b22b530965?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    link: "https://github.com/Charles6489/esp8266-get",
    site: "https://www.youtube.com/watch?v=DjXhDnkmuNo&feature=youtu.be",
    description: "MQTT-ESP8266",
  },
  {
    id: 2,
    title: "GooGle Cloud",
    img: "https://images.unsplash.com/photo-1604003567179-a467f97bd200?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80",
    link: "https://github.com/Charles6489/esp8266-get",
    site: "https://www.youtube.com/watch?v=eidRBIPeYoY",
    description: "MQTT-ESP8266",
  },
  {
    id: 3,
    title: "AWS",
    img: "assets/images/img-1.jpg",
    link: "https://github.com/Charles6489/modbus_arduino_factory_io_nodered",
    site: "https://www.youtube.com/watch?v=FHhumt2GADU",
    description: "MQTT-ESP8266",
  },

  {
    id: 1,
    title: "Pagina Web",
    img: "assets/images/civil.png",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/Civil/",
  },
  {
    id: 2,
    title: "Pagina Web",
    img: "assets/images/page1.png",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/Pagina1/",
  },
  {
    id: 3,
    title: "Pagina Web",
    img: "assets/images/page2.png",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/React2/",
  },
];

export const webPortfolio = [
  {
    id: 1,
    title: "Pagina Web",
    img: "assets/images/civil.png",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/Civil/",
  },
  {
    id: 2,
    title: "Pagina Web",
    img: "assets/images/page1.png",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/Pagina1/",
  },
  {
    id: 3,
    title: "Pagina Web",
    img: "assets/images/page2.png",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/React2/",
  },
  {
    id: 4,
    title: "Pagina Web",
    img: "assets/images/tienda.png",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/electrocode/",
  },
  {
    id: 5,
    title: "Pagina Web",
    img: "assets/images/ejemplo.png",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/pruebaweb/",
  },
  {
    id: 6,
    title: "Pagina Web",
    img: "assets/images/things.png",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/thingslearned/",
  },
  {
    id: 7,
    title: "Pagina Web",
    img: "https://images01.nicepage.com/page/42/02/website-template-preview-42023.jpg",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/food/",
  },
  {
    id: 8,
    title: "Pagina Web",
    img: "assets/images/screencapture-corozco6489-github-io-Bootstrap5Simple-2021-10-18-08_45_57.png",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/Bootstrap5Simple/",
  },
];

export const mobilePortfolio = [
  {
    id: 1,
    title: "GooGle Cloud",
    img: "https://images.unsplash.com/photo-1603695576504-b2b22b530965?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    link: "https://github.com/Charles6489/esp8266-get",
    site: "https://www.youtube.com/watch?v=DjXhDnkmuNo&feature=youtu.be",
    description: "MQTT-ESP8266",
  },
  {
    id: 2,
    title: "GooGle Cloud",
    img: "https://images.unsplash.com/photo-1604003567179-a467f97bd200?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80",
    link: "https://github.com/Charles6489/esp8266-get",
    site: "https://www.youtube.com/watch?v=eidRBIPeYoY",
    description: "MQTT-ESP8266",
  },
  {
    id: 3,
    title: "AWS",
    img: "assets/images/img-1.jpg",
    link: "https://github.com/Charles6489/modbus_arduino_factory_io_nodered",
    site: "https://www.youtube.com/watch?v=FHhumt2GADU",
    description: "MQTT-ESP8266",
  },
];

export const designPortfolio = [
  {
    id: 1,
    title: "Weather App",
    img: "assets/images/wheaterapp.png",
    link: "https://github.com/corozco6489/miniprojects-python/blob/password-generator/wheaterapi.py",
    site: "https://github.com/corozco6489/miniprojects-python/blob/password-generator/wheaterapi.py",
  },
  {
    id: 2,
    title: "ChatBot Telegram Arduino",
    img: "https://codingornot.com/wp-content/uploads/2018/07/chatbot-con-telegram-python-y-arduino.png",
    link: "https://github.com/corozco6489/Proyecto-Telegram--Chatbot---Arduino---ESP32CAM",
    site: "https://www.youtube.com/watch?v=_fL-Wqhd-xs",
    description: "ARDUINO - TELEGRAM",
  },
  {
    id: 3,
    title: "Calculator App",
    img: "assets/images/calculator.png",
    link: "https://github.com/corozco6489/miniprojects-python/blob/password-generator/Calculator.py",
    site: "https://github.com/corozco6489/miniprojects-python/blob/password-generator/Calculator.py",
  },
  {
    id: 4,
    title: "Scientific Calculator",
    img: "assets/images/scientific_calculator.png",
    link: "https://github.com/corozco6489/miniprojects-python/blob/password-generator/calculator_cientific/Scientific_calculator.py",
    site: "https://github.com/corozco6489/miniprojects-python/blob/password-generator/calculator_cientific/Scientific_calculator.py",
  },
];

export const contentPortfolio = [
  {
    id: 1,
    title: "Optical Character Recognition",
    img: "https://la.mathworks.com/matlabcentral/mlc-downloads/downloads/daea137a-5cd3-485e-9855-ceef8b7ce951/8c87c747-d9db-4653-b2e8-893d4e4cc9b2/images/1617204293.PNG",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89654-optical-character-recognition-ocr?s_tid=srchtitle",
    site: "https://www.youtube.com/watch?v=Ns0gigWsijE",
    description: "(OCR)",
  },
  {
    id: 2,
    title: "Codigos de Lineas",
    img: "https://la.mathworks.com/matlabcentral/mlc-downloads/downloads/b6086d6c-2c90-4677-99c2-83b59ec84502/2c24a7ad-410a-4af9-85cd-3ee766cd9b30/images/1618269106.png",
    link: "https://www.mathworks.com/matlabcentral/fileexchange/89461-codigos-de-lineas",
    site: "https://www.youtube.com/watch?v=Ns0gigWsijE",
    description: "Matlab - Guide",
  },
  {
    id: 3,
    title: "fourier series",
    img: "https://la.mathworks.com/matlabcentral/mlc-downloads/downloads/7544ce00-76bb-40dd-ae64-bdac9554629a/6e7e6cb0-aa24-47a7-a1a1-ed865e9ecee9/images/1616884439.PNG",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89471-fourier-series",
    site: "https://www.youtube.com/watch?v=A4pPMjUCpu4",
    description: "Matlab - Guide",
  },
  {
    id: 4,
    title: "Transformada de Fourier",
    img: "https://la.mathworks.com/matlabcentral/mlc-downloads/downloads/0926d5af-689c-4525-970f-ddc28ce62037/e742d0c9-67cc-41df-85fd-0960e97b6e38/images/1616884683.PNG",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89476-fourier-transform",
    site: "https://www.youtube.com/watch?v=mFPzV0_ZAaU",
    description: "Matlab - Guide",
  },
  {
    id: 5,
    title: "Antena de Onda Progresiva",
    img: "https://la.mathworks.com/matlabcentral/mlc-downloads/downloads/99531845-4005-4440-8ddb-0cc5104f4062/63b04383-fcaf-45a5-b662-d9ab57f3734c/images/1616882985.PNG",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89466-antena-de-onda-progresiva",
    site: "https://www.youtube.com/watch?v=PGiCUdlkhHw",
    description: "Matlab - Guide",
  },
  {
    id: 6,
    title: "SINGLE STUB SHUNT TUNING",
    img: "https://la.mathworks.com/matlabcentral/mlc-downloads/downloads/742c566e-a278-4e8d-b29c-08f79fb3060a/ff2c2392-d99b-4f5a-b3e5-c6fc117f34e1/images/1616880509.PNG",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89451-single-stub-shunt-tuning",
    site: "https://www.youtube.com/watch?v=g3iBlooyHTw",
    description: "Matlab - Guide",
  },
  {
    id: 7,
    title: "SINGLE STUB SERIES TUNING",
    img: "https://la.mathworks.com/matlabcentral/mlc-downloads/downloads/a4832235-7133-4809-8081-ccfac616edcf/023bc73a-8024-4c03-be78-763983a7eefd/images/1616892993.PNG",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89486-single-stub-series-tuning",
    site: "https://www.youtube.com/watch?v=1RVlOyMxK_k",
    description: "Matlab - Guide",
  },
  {
    id: 8,
    title: "Procesamiento de Imagenes",
    img: "https://i.ytimg.com/vi/12cHkBRj3QY/maxresdefault.jpg",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/96942-proyecto-modulaciones-digitales-aplicado-a-imagenes-matlab",
    site: "https://www.youtube.com/watch?v=12cHkBRj3QY",
    description: "Matlab - Guide",
  },
  {
    id: 9,
    title: "Log Periodic Dipole Antenna",
    img: "https://i.ytimg.com/vi/UgPA1TDpH7Q/mqdefault.jpg",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/96872-log-periodic-antenna",
    site: "https://www.youtube.com/watch?v=eCaaMCwWpmY",
    description: "Matlab - Guide",
  },
  {
    id: 10,
    title: "Modulacion PCM",
    img: "https://i.ytimg.com/vi/2jk2lun9zBs/maxresdefault.jpg",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/97107-modulacion-pcm?s_tid=srchtitle",
    site: "https://www.youtube.com/watch?v=2jk2lun9zBs",
    description: "Matlab - Guide",
  },
];

export const reactPortfolio = [
  {
    id: 1,
    title: "Portfolio Dark mode",
    img: "assets/images/react1.png",
    link: "https://github.com/corozco6489/Portfolio-dark-mode",
    site: "https://corozco6489.github.io/Portfolio-dark-mode/",
    description: "Responsive multicolor portfolio page using React and CSS.",
  },
  {
    id: 2,
    title: "Portfolio",
    img: "assets/images/react3.png",
    link: "https://github.com/corozco6489/Orozco",
    site: "https://faztcode.tk/",
    description:
      "Responsive React portfolio website using functional components and React hooks with Sass.",
  },
  {
    id: 3,
    title: "E-Commerce Application",
    img: "assets/images/react4.png",
    link: "https://github.com/corozco6489/Ecommerce",
    site: "https://corozco6489.github.io/Ecommerce/",
    description: "Website from scratch using React.js",
  },
  {
    id: 4,
    title: "Chat Application",
    img: "assets/images/react5.png",
    link: "https://github.com/corozco6489/Chat-Application",
    site: "https://corozco6489.github.io/Chat-Application/",
    description:
      "Chat Application with react chat engine , socket , rest api    login: admin   password:admin",
  },
  {
    id: 5,
    title: "Video Sharing Web App",
    img: "assets/images/youtube.png",
    link: "https://github.com/corozco6489/youtubeapi",
    site: "https://corozco6489.github.io/youtubeapi/",
    description:
      "Video Sharing Web App using youtube api , material-ui , axios",
  },
];

export const habilidades = [
  {
    id: 1,
    title: "Arduino",
    img: "assets/images/works/pngegg.png",
  },
  {
    id: 2,
    title: "LabView",
    img: "assets/images/works/labview.png",
  },
  {
    id: 3,
    title: "Matlab",
    img: "assets/images/works/matlab.png",
  },
  {
    id: 4,
    title: "Proteus",
    img: "assets/images/works/proteus.png",
  },
  {
    id: 5,
    title: "Python",
    img: "assets/images/works/python.png",
  },
  {
    id: 6,
    title: "Linux",
    img: "assets/images/works/linux.png",
  },
  {
    id: 6,
    title: "React",
    img: "assets/images/works/react.png",
  },
  {
    id: 6,
    title: "SQL",
    img: "assets/images/works/sql.png",
  },
  {
    id: 6,
    title: "Raspberry",
    img: "assets/images/works/rasberry.png",
  },
  {
    id: 6,
    title: "Node Red",
    img: "assets/images/works/node.png",
  },
  {
    id: 6,
    title: "Virtual Box",
    img: "assets/images/works/virtual.png",
  },
  {
    id: 6,
    title: "Factory IO",
    img: "assets/images/works/factory.png",
  },
  {
    id: 6,
    title: "AWS",
    img: "assets/images/works/aws.png",
  },
  {
    id: 6,
    title: "Linux",
    img: "assets/images/works/pngegg.png",
  },
  {
    id: 6,
    title: "Multisim",
    img: "assets/images/works/multisim.png",
  },
  {
    id: 6,
    title: "Microsoft Office",
    img: "assets/images/works/office.png",
  },
  {
    id: 6,
    title: "Adobe Photoshop",
    img: "assets/images/works/adobe.png",
  },
  {
    id: 6,
    title: "DaVinci Resolve",
    img: "assets/images/works/davin.png",
  },
];

export const certificaciones = [
  {
    id: 1,
    title: "Talleres de redes y ciberseguridad",
    img: "assets/images/certificados/0.jpg",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:"  2021",
    description: " En colaboración con el Grupo de Afinidad Young Professionals de Sección Ecuador y las empresas Kp@8 y Avantech Latam.",
  },
  {
    id: 1,
    title: "Habilidades blandas y derecho laboral",
    img: "assets/images/certificados/1.jpg",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:"  2021",
    description: " En colaboración con el Grupo de Afinidad Young Professionals de Sección Ecuador y las empresas Kp@8 y Avantech Latam.",
  },

  {
    id: 1,
    title: "Introducción al Marketing Digital",
    img: "assets/images/certificados/2.jpg",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:"  2021",
    description: " En colaboración con el Grupo de Afinidad Young Professionals de Sección Ecuador y las empresas Kp@8 y Avantech Latam.",
  },
  {
    id: 1,
    title: "Técnico en instalación y repación de equipo de cómputo",
    img: "assets/images/certificados/3.jpg",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:"  2022",
    description: " En colaboración con el Grupo de Afinidad Young Professionals de Sección Ecuador y las empresas Kp@8 y Avantech Latam.",
  },
  {
    id: 1,
    title: "Técnico en reparación de laptops",
    img: "assets/images/certificados/12.jpg",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:"  2022",
    description: " En colaboración con el Grupo de Afinidad Young Professionals de Sección Ecuador y las empresas Kp@8 y Avantech Latam.",
  },
  {
    id: 1,
    title: "Electrónica Basica",
    img: "assets/images/certificados/4.png",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:"  2022",
    description: " En colaboración con el Grupo de Afinidad Young Professionals de Sección Ecuador y las empresas Kp@8 y Avantech Latam.",
  },
  {
    id: 1,
    title: "Disciplina en el trabajo",
    img: "assets/images/certificados/5.jpg",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:"  2022",
    description: " En colaboración con el Grupo de Afinidad Young Professionals de Sección Ecuador y las empresas Kp@8 y Avantech Latam.",
  },
  {
    id: 1,
    title: "Competencias digitales para profesionales",
    img: "assets/images/certificados/6.jpg",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:"  2022",
    description: " En colaboración con el Grupo de Afinidad Young Professionals de Sección Ecuador y las empresas Kp@8 y Avantech Latam.",
  },
  {
    id: 1,
    title: "Protege tu Negocio: Ciberseguridad en el Teletrabajo",
    img: "assets/images/certificados/7.jpg",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:"  2022",
    description: " En colaboración con el Grupo de Afinidad Young Professionals de Sección Ecuador y las empresas Kp@8 y Avantech Latam.",
  },
  {
    id: 1,
    title: "Control de versiones Git y Github",
    img: "assets/images/certificados/8.jpg",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:"  2022",
    description: " En colaboración con el Grupo de Afinidad Young Professionals de Sección Ecuador y las empresas Kp@8 y Avantech Latam.",
  },
  {
    id: 1,
    title: "Liderazgo",
    img: "assets/images/certificados/9.jpg",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:"  2022",
    description: " En colaboración con el Grupo de Afinidad Young Professionals de Sección Ecuador y las empresas Kp@8 y Avantech Latam.",
  },
  {
    id: 1,
    title: "Productividad Personal",
    img: "assets/images/certificados/10.jpg",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:"  2022",
    description: " En colaboración con el Grupo de Afinidad Young Professionals de Sección Ecuador y las empresas Kp@8 y Avantech Latam.",
  },
  {
    id: 1,
    title: "Programación desde Cero (Python)",
    img: "assets/images/certificados/11.png",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:"  2022",
    description: " En colaboración con el Grupo de Afinidad Young Professionals de Sección Ecuador y las empresas Kp@8 y Avantech Latam.",
  },
  {
    id: 1,
    title: "Learn SQL Course",
    img: "assets/images/certificados/18.jpg",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:"  2022",
    description: " En colaboración con el Grupo de Afinidad Young Professionals de Sección Ecuador y las empresas Kp@8 y Avantech Latam.",
  },
   {
    id: 1,
    title: "Curso Hacking Wi-Fi",
    img: "assets/images/certificados/13.png",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:"  2022",
    description: " En colaboración con el Grupo de Afinidad Young Professionals de Sección Ecuador y las empresas Kp@8 y Avantech Latam.",
  },
  {
    id: 1,
    title: "Cableado Estructurado Residencial y para Comercios Pequeños",
    img: "assets/images/certificados/13.jpg",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:"  2022",
    description: " En colaboración con el Grupo de Afinidad Young Professionals de Sección Ecuador y las empresas Kp@8 y Avantech Latam.",
  },
  {
    id: 1,
    title: "Sistemas de automatización residencial​",
    img: "assets/images/certificados/14.jpg",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:"  2022",
    description: " En colaboración con el Grupo de Afinidad Young Professionals de Sección Ecuador y las empresas Kp@8 y Avantech Latam.",
  },
  {
    id: 1,
    title: "Técnico en informática (Ofimática)​",
    img: "assets/images/certificados/15.jpg",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:"  2022",
    description: " En colaboración con el Grupo de Afinidad Young Professionals de Sección Ecuador y las empresas Kp@8 y Avantech Latam.",
  },

  {
    id: 1,
    title: "Técnico en seguridad informática (análisis de riesgos)",
    img: "assets/images/certificados/16.jpg",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:"  2022",
    description: " En colaboración con el Grupo de Afinidad Young Professionals de Sección Ecuador y las empresas Kp@8 y Avantech Latam.",
  },

  {
    id: 1,
    title: "Seguridad Informática y Redes",
    img: "assets/images/certificados/17.jpg",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:"  2022",
    description: " En colaboración con el Grupo de Afinidad Young Professionals de Sección Ecuador y las empresas Kp@8 y Avantech Latam.",
  },


  {
    id: 1,
    title: "Principios básicos de Internet de las Cosas",
    img: "assets/images/certificados/19.jpg",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:"  2022",
    description: " En colaboración con el Grupo de Afinidad Young Professionals de Sección Ecuador y las empresas Kp@8 y Avantech Latam.",
  },
  {
    id: 1,
    title: "Técnico instalador de cableado estructurado",
    img: "assets/images/certificados/20.jpg",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:"  2022",
    description: " En colaboración con el Grupo de Afinidad Young Professionals de Sección Ecuador y las empresas Kp@8 y Avantech Latam.",
  },
  {
    id: 1,
    title: "Office Básico",
    img: "assets/images/certificados/21.jpg",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:"  2022",
    description: " En colaboración con el Grupo de Afinidad Young Professionals de Sección Ecuador y las empresas Kp@8 y Avantech Latam.",
  },

]